1. Implement the function S = IsSquare(A) that checks the dimension of input matrix A, and returns 1 if the input matrix is square and 0 otherwise

In [2]:
import numpy as np

def isSquare(A):
    if A.shape[0] == A.shape[1]:
        return 1
    else:
        return 0

x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,2],[3,4]])
print(isSquare(x))
print(isSquare(y))

0
1


2. Implement the function N = Props(A) that checks the properties of the input matrix A:
 2.1 checks the input matrix is square,
 2.2 computes the matrix rank, prints the rank value (hint: use numpy method)
 2.3 computes the matrix determinant (hint: use numpy method) and prints its value
 2.4 returns 1 if the input matrix has rank = no. of rows in matrix A and 0 otherwise

In [3]:
# Implement the function N = Props(A) that checks the properties of the input matrix A:
def Props(A):
    #  2.1 checks the input matrix is square,
    if isSquare(A) == 1:
        print("The input matrix is square.")
    else:
        print("The input matrix is not square.")
    #  2.2 computes the matrix rank, prints the rank value (hint: use numpy method)
    print("The rank of the input matrix is: ", np.linalg.matrix_rank(A))
    #  2.3 computes the matrix determinant (hint: use numpy method) and prints its value
    if(isSquare(A) == 1):
        print("The determinant of the input matrix is: ", np.linalg.det(A))
    else:
        print("The determinant of the input matrix is: ", "Not applicable.")
    #  2.4 returns 1 if the input matrix has rank = no. of rows in matrix A and 0 otherwise
    if np.linalg.matrix_rank(A) == A.shape[0]:
        print("The input matrix has rank = no. of rows in matrix A.")
    else:
        print("The input matrix has rank < no. of rows in matrix A.")

Props(x)


The input matrix is not square.
The rank of the input matrix is:  2
The determinant of the input matrix is:  Not applicable.
The input matrix has rank = no. of rows in matrix A.


Compose the equations corresponding to the two word-problems below and put
them in matrix-vector form AX = B. Call "Props" to find more about their properties.

In [4]:
A1 = np.array([[1,1,1],[1.5,5.75,2.6], [0,-1,1]])
A2 = np.array([[2,1,3],[4,2,6],[1,1,-1]])
Props(A1)
print()
Props(A2)

The input matrix is square.
The rank of the input matrix is:  3
The determinant of the input matrix is:  5.35
The input matrix has rank = no. of rows in matrix A.

The input matrix is square.
The rank of the input matrix is:  2
The determinant of the input matrix is:  0.0
The input matrix has rank < no. of rows in matrix A.


4. Implement the function reducerow(C,pivotrow,targetrow,pivot)
 4.1 Takes an input matrix C, index of a pivot row vector, index of a target row vector,
index of a pivot element. It returns nothing but overrides the matrix C
 4.2 Checks if the pivot element = 1 otherwise perform vector operation to make it = 1
 4.3 Uses vector operations using the two vectors “pivotrow” & “targetrow” to make
the element corresponding to the pivot element in the targetrow vector = 0

In [5]:
# Implement the function reducerow(C,pivotrow,targetrow,pivot)
def reducerow(C,pivotrow,targetrow,pivot):
    if C[pivotrow,pivot]!=1:
        C[pivotrow,:]=C[pivotrow,:]/C[pivotrow][pivot]
    C[targetrow,:]=C[targetrow,:]-C[targetrow,pivot]*C[pivotrow,:]
    return C

# # make numpy array 3x3
A = np.array([[7,2,3],[4,5,6],[7,8,9]])
print(A)
reducerow(A,0,1,1)
print(A)


[[7 2 3]
 [4 5 6]
 [7 8 9]]
[[  3   1   1]
 [-11   0   1]
 [  7   8   9]]


5. Implement the function f = SolveLinearSystem (A,B)
 5.1 Takes as an input coefficient matrix A and target vector B
 5.2 Adjoins A and B then perform row reduction operations using “reducerow” trying
to convert it A’s columns into an identity matrix
 5.3 returns f = the summation of A’s columns elements after row reduction

In [6]:
# Implement the function f = SolveLinearSystem (A,B) Takes as an input coefficient matrix A and target vector B
# def solveLinearSystem(A,B):
#     #  3.1 check if the input matrix is square
#     if isSquare(A) == 1:
#         #  3.2 check if the rank of the input matrix is equal to the number of rows in the matrix A
#         if np.linalg.matrix_rank(A) == A.shape[0]:
#             #  3.3 check if the determinant of the input matrix is not equal to zero
#             if np.linalg.det(A) != 0:
#                 #  3.4 compute the solution vector f
#                 f = np.linalg.solve(A,B)
#                 return f
#             else:
#                 print("The determinant of the input matrix is zero.")
#         else:
#             print("The rank of the input matrix is not equal to the number of rows in the matrix A.")
#     else:
#         print("The input matrix is not square.")

In [7]:
# 5.1 Takes as an input coefficient matrix A and target vector B
def solveLinearSystem(A, B):
    # 5.2 Adjoins A and B then perform row reduction operations using “reducerow” trying to convert it A’s columns into an identity matrix
    C = np.concatenate((A,B),axis=1)
    # 5.3 Computes the inverse of A using the reduced matrix C
    # 5.3 returns f = the summation of A’s columns elements after row reduction
    for i in range(A.shape[0]):
        for j in range(B.shape[0]):
            if i!=j:
                C = reducerow(C,i,j,i)
    # returns f = the summation of A’s columns elements after row reduction
    f = np.zeros(A.shape[0])
    
    # print(C[:,0])
    for i in range(A.shape[0]):
        f[i] = np.sum(C[:,i], axis=0)
    f = f.sum()
    # f = np.sum(C[:,:A.shape[0]])
    return C, f

# coefficient matrix
A = np.array([[2,0,-6],[0,1,2],[3,6,-2]])
# target vector
B = np.array([[-8],[3],[-4]])
solveLinearSystem(A,B)


(array([[ 1,  0,  0,  2],
        [ 0,  1,  0, -1],
        [ 0,  0,  1,  2]]),
 3.0)

6. Call “SolveLinearSystem” to solve the systems 1 and 2 you previously created in 3

In [8]:
# 6. Call “SolveLinearSystem” to solve the systems 1 and 2 you previously created in 3
# Compose the equations corresponding to the two word-problems below and put
# them in matrix-vector form AX = B. Call "Props" to find more about their properties.
# System 1:
# A wedding planner ordered 200 flowers for tables decorations.
# He ordered sunflowers at $1.50 each, roses at $5.75 each and daisies at $2.60 each.
# He ordered mostly sunflowers and 20 fewer roses than daisies.
# The total order came to $589.5. How many of each type of flower was ordered?

A1 = np.array([[1,1,1],[1.5,5.75,2.6], [0,-1,1]])
B1 = np.array([[200],[589.5],[20]])

solveLinearSystem(A1,B1)


(array([[ 1.,  0.,  0., 80.],
        [ 0.,  1.,  0., 50.],
        [ 0.,  0.,  1., 70.]]),
 3.0)

In [12]:
# System 2:
# A food-cart owner regularly buys oil to fry the chicken and potatoes he sells.
# Sometimes he doesn't sell well but he needs to keep buying oil anyways. In three consecutive days
# he made zero profit. In the first day, he sold 2 packs of potatoes and 1 pack of chicken
# but had to buy 3 bottles of oil. In the second day, he sold 4 packs of potatoes and 2 pack
# of chicken but had to buy 6 bottles of oil. In the third day, he sold 1 pack of potatoes
# and a friend gave him 1 bottle of oil and took 1 pack of chicken instead. What were the
# prices of the chicken, potatoes and oil?
A2 = np.array([[2,1,3],[4,2,6],[1,1,-1]])
B2 = np.array([0,0,0])
solveLinearSystem(A2,B2)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Elaborate your solution (write commented text)
    7.1 If f<3 explain the reason and propose one possible solution (if any) to the equation system
    7.2 otherwise write down the system solution

In [9]:
Ax = np.array([[1,0,0],[0,1,0], [0,0,0]])
Bx = np.array([[200],[400],[0]])

solveLinearSystem(Ax,Bx)
# since the 2nd row is dependent on the first row, we get f = 5, which is the solution to the system
# in System 1, f was 3 which meant an independent system of equations (since it was 3x3 matrix)
# but in System 2, the rank of the input matrix is not equal to the number of rows in the matrix A2


C:\Users\Public\Documents\Wondershare\CreatorTemp/ipykernel_27164/3972044671.py:4: RuntimeWarning: invalid value encountered in true_divide
  C[pivotrow,:]=C[pivotrow,:]/C[pivotrow][pivot]


(array([[  1,   0,   0, 200],
        [  0,   1,   0, 400],
        [  1,   1,   1,   1]]),
 5.0)

8. Type these code lines and check your answers for systems 1 and 2
    x = np.linalg.solve(A, B) # Solves a full-rank system of linear equations ax = b.
    print(x)
    np.allclose(np.dot(A, x), B) # Returns True if two arrays are element-wise equal within a
    tolerance.

In [10]:
x = np.linalg.solve(A1, B1) # Solves a full-rank system of linear equations ax = b.
print(x)
np.allclose(np.dot(A1, x), B1) # Returns True if two arrays are element-wise equal within a tolerance.

[[80.]
 [50.]
 [70.]]


True

In [13]:
x = np.linalg.solve(A2, B2) # Solves a full-rank system of linear equations ax = b.
print(x)
np.allclose(np.dot(A2, x), B2) # Returns True if two arrays are element-wise equal within a tolerance.

LinAlgError: Singular matrix

9. Call the same function “SolveLinearSystem” to get inv(A) for systems 1 and 2

In [14]:
# Call the same function “SolveLinearSystem” to get inv(A) for systems 1 and 2
# create identity matrix 3x3
I = np.identity(3)

solveLinearSystem(A1,I)

(array([[ 1.        ,  0.        ,  0.        ,  1.56074766, -0.37383178,
         -0.58878505],
        [ 0.        ,  1.        ,  0.        , -0.28037383,  0.18691589,
         -0.20560748],
        [ 0.        ,  0.        ,  1.        , -0.28037383,  0.18691589,
          0.79439252]]),
 3.0)

10. Check your solution if possible using np.linalg.inv() function

In [15]:
np.linalg.inv(A1) # Returns the inverse of a matrix.

array([[ 1.56074766, -0.37383178, -0.58878505],
       [-0.28037383,  0.18691589, -0.20560748],
       [-0.28037383,  0.18691589,  0.79439252]])

In [16]:
np.linalg.inv(A2) # Returns the inverse of a matrix.

LinAlgError: Singular matrix